### ISSUE TITLE
Add Cargo.lock in versions.

### ISSUE THREAD

**Issue by rambip** [bytecodealliance/cargo-wasi#101]
This project is really cool, and I'm trying to wrap it into a nix expression so that people can get this tool from nix directly, to install it in the nix-store and without installation issues.
This have been done for [cargo-watch](https://search.nixos.org/packages?channel=21.05&show=cargo-watch&from=0&size=50&sort=relevance&query=cargo-watch).
This is really simple to create a nix-expression for a derivation with a rust program, you have the example for `cargo-watch` [here](https://github.com/NixOS/nixpkgs/blob/nixos-21.05/pkgs/development/tools/rust/cargo-watch/default.nix#L25)

And to do that, I would just need a Cargo.lock, to create a hash of it and get a reproducible build.
(and this is best practise to add this file to a repository anyway).

Is that possible ?

**Comment by alexcrichton** [comment]
This crate is intended to work with the latest versions of dependencies since it's `cargo install`-able, so it's intentional that there's not a `Cargo.lock` in this repository. This project isn't really big enough to require one.

If you'd like to have reproducible builds on your side I'd recommend vendoring your own `Cargo.lock` for your packaging needs.
